name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  PACKAGES: "iqm-pulse iqm-exa-common iqm-station-control-client iqm-pulla iqm-benchmarks qiskit-iqm cirq-iqm iqm-client"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          apt-get update
          apt-get install -y graphviz

      - name: Build sphinx documentation
        run: |
          mkdir -p public
          mkdir -p temp
          cd temp

          for package in $PACKAGES; do
            echo "Processing $package..."
            # download source distribution
            python -m pip download --no-deps --no-binary :all: $package
            echo "installing package (required for namespace resolution when building docs with Sphinx)..."
            python -m pip install $package
            echo "unarchiving source distribution and cd-ing into the resulting directory..."
            tar -xvzf *.tar.gz
            cd "$(tar -tzf *.tar.gz | head -1 | cut -f1 -d"/")"
            echo "building docs..."
            python -m sphinx docs ../../public/$package
            # add .nojekyll in order to stop Github from treating the directory as a Jekyll blog generator, 
            # which ignores directories starting with underscore
            touch ../../public/$package/.nojekyll
            echo "cleaning up..."
            cd ..
            rm -rf *
          done

          cd ..
          rm -rf temp
          rm -rf public/jupyter_execute
          touch public/.nojekyll

      - name: Generate search index
        run: python generate_search_index.py

      - name: Ensure search index is in public folder
        run: |
          cp search.json public/ || echo "No search index found"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install and build React project
        run: |
          npm ci
          npm run build
  
      - name: Copy React build to public folder
        run: |
          mkdir -p public
          cp -r dist/* public/
          cp src/favicon.ico public/favicon.ico

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
